# Site settings
title: Elemium 466
email: your-email@domain.com
url: https://elemium466.github.io
description: "Elements of Machine Learning for Algorithmic Trading & Risks"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Ei466

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
#  - title: twitter
#   url: https://twitter.com/SBootstrap
#  - title: facebook
#    url:
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket
#    url: http://bitbucket.org/jekyll
social:
  - title: github
    url: https://github.com/elemium466/

# Build settings
markdown: kramdown
permalink: pretty
