# Site settings
title: Elemium 466
email: your-email@domain.com
url: https://elemium466.github.io
description: "Elements of Machine Learning for Algorithmic Trading & Risks"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#e6e620'

# Footer settings
footer: Ei466

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
#  - title: twitter
#   url: https://twitter.com/SBootstrap
#  - title: facebook
#    url:
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket
#    url: http://bitbucket.org/jekyll
#  - title: github
#    url: https://github.com/elemium466/
social:
  - title: linkedin
    url: https://www.linkedin.com/in/baptiste-d-ml

# Build settings
markdown: kramdown
permalink: pretty
